/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AppIndexRouteImport } from './pages/_app/index'
import { Route as AppWorkflowIdRouteImport } from './pages/_app/workflow/$id'

const AppIndexRoute = AppIndexRouteImport.update({
  id: '/_app/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkflowIdRoute = AppWorkflowIdRouteImport.update({
  id: '/_app/workflow/$id',
  path: '/workflow/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/workflow/$id': typeof AppWorkflowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/workflow/$id': typeof AppWorkflowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app/': typeof AppIndexRoute
  '/_app/workflow/$id': typeof AppWorkflowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/workflow/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/workflow/$id'
  id: '__root__' | '/_app/' | '/_app/workflow/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppWorkflowIdRoute: typeof AppWorkflowIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workflow/$id': {
      id: '/_app/workflow/$id'
      path: '/workflow/$id'
      fullPath: '/workflow/$id'
      preLoaderRoute: typeof AppWorkflowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppWorkflowIdRoute: AppWorkflowIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
