/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as AppIndexRouteImport } from './pages/_app/index'
import { Route as AppIdRouteImport } from './pages/_app/$id'

const AppIndexRoute = AppIndexRouteImport.update({
  id: '/_app/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIdRoute = AppIdRouteImport.update({
  id: '/_app/$id',
  path: '/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/$id': typeof AppIdRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/$id': typeof AppIdRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app/$id': typeof AppIdRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/$id' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/$id' | '/'
  id: '__root__' | '/_app/$id' | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppIdRoute: typeof AppIdRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/$id': {
      id: '/_app/$id'
      path: '/$id'
      fullPath: '/$id'
      preLoaderRoute: typeof AppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AppIdRoute: AppIdRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
